server:
  port: 9490
spring:
  application:
    name: jay-zuul
feign:
  #feign开启熔断器
  hystrix:
    enabled: true
    #开启feign的压缩功能
  compression:
    request:
      enabled: true
    response:
      enabled: true
hystrix:
  command:
    #全局超时时间(<commandKey>作为前缀,默认是采用Feign的客户端的方法名字作为标识,defaul可以改为具体的@HystrixCommand中commandKey)
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

eureka:
  instance:
    hostname: localhost
    #服务续约，心跳的时间间隔
    lease-renewal-interval-in-seconds: 30
    #如果从前一次发送心跳时间起，90秒没接受到新的心跳，讲剔除服务
    lease-expiration-duration-in-seconds=90:
  client:
    #是否注册到eureka
    fetchRegistry: true
    #是否从eureka中拉取注册信息
    registerWithEureka: true
    ##暴露eureka服务的地址
    serviceUrl:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:9090/eureka/
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    registry-fetch-interval-seconds: 30
    #健康检测
    healthcheck:
      enabled: true


#====================business config ↓===========================

#====================business config ↑===========================